# Generated by Django 4.1.7 on 2023-04-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect', models.CharField(max_length=6, verbose_name='Звідки')),
                ('to', models.CharField(max_length=6, verbose_name='Куди')),
            ],
        ),
    ]
