# Generated by Django 4.1.7 on 2023-04-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectlink',
            name='to',
            field=models.URLField(max_length=254, verbose_name='Куди'),
        ),
    ]
